import LegalPage from "../_components/LegalPage";
import { businessIdentity } from "../_data/legal";

export const metadata = { title: "Conditions générales de vente — Animation Made", description: "Conditions applicables aux prestations et cours proposés par Animation Made.", alternates: { canonical: "/nouveau/cgv" } };

export default function TermsPage() {
  return <LegalPage eyebrow="CONDITIONS DE VENTE" title={<>Conditions générales <em>de vente.</em></>} intro="Ces conditions encadrent les prestations personnalisées et les cours achetés sur Animation Made par des clients particuliers.">
    <section><h2>1. Identité et champ d’application</h2><p>Les présentes conditions sont proposées par {businessIdentity.owner}, entrepreneure individuelle exploitant Animation Made, SIRET {businessIdentity.siret}, domiciliée {businessIdentity.address}. Contact : <a href={`mailto:${businessIdentity.email}`}>{businessIdentity.email}</a> — {businessIdentity.phoneLabel}. {businessIdentity.vat}.</p><p>Elles s’appliquent aux commandes passées sur le site par des consommateurs. La version acceptée au moment de la commande prévaut.</p></section>
    <section><h2>2. Prestations proposées</h2><p>Animation Made propose des feedbacks d’animation annotés, des reviews de book ou showreel, un accompagnement de projet d’animation, une fiche personnalisée de direction de contenu et des cours d’anglais en visioconférence, à l’unité ou en pack.</p><p>Le contenu, le format, les limites et le délai propres à chaque offre sont rappelés sur sa page et dans le récapitulatif précédant le paiement. Les conseils constituent un accompagnement créatif et pédagogique : aucun recrutement, résultat professionnel, audience, revenu ou niveau précis ne peut être garanti.</p></section>
    <section><h2>3. Commande</h2><p>La commande devient ferme lorsque le client a vérifié son récapitulatif, accepté les présentes conditions et effectué le paiement. Un e-mail ou un écran de confirmation récapitule la commande. Animation Made peut demander les éléments manquants indispensables avant de commencer la prestation.</p><p>Le client s’engage à fournir des informations exactes, des liens accessibles et des fichiers qu’il est autorisé à partager. Il conserve une copie des originaux.</p></section>
    <section><h2>4. Prix et paiement</h2><p>Les prix sont indiqués en euros, toutes taxes comprises lorsqu’une taxe est applicable. À ce jour : {businessIdentity.vat.toLowerCase()}. Le prix affiché dans le dernier récapitulatif avant paiement est le prix contractuel.</p><p>Le paiement est effectué en ligne par carte bancaire via le prestataire de paiement indiqué lors du checkout. Animation Made ne reçoit ni ne conserve les numéros complets de carte. La commande n’est traitée qu’après confirmation du paiement.</p></section>
    <section><h2>5. Délais et livraison</h2><p>Les prestations écrites ou annotées sont remises dans l’espace client ou par le moyen annoncé lors de la commande. Les délais commencent après réception du paiement et de tous les éléments nécessaires : 7 jours pour la review de book, le feedback d’animation et chaque étape annoncée du projet d’animation ; 10 jours pour la fiche de direction de contenu.</p><p>Si un élément manque, le délai est suspendu jusqu’à sa réception. En cas d’imprévu empêchant de respecter le délai annoncé, le client est informé. Les recours légaux en cas de retard restent applicables.</p></section>
    <section><h2>6. Cours d’anglais et rendez-vous</h2><p>Les cours ont lieu en visioconférence, actuellement via Google Meet. Le cours individuel dure une heure. Le cours en duo réunit deux personnes sur le même lien et fait l’objet d’un paiement unique. Les packs de 4 heures sont utilisables sous 3 mois et ceux de 8 heures sous 6 mois à compter de l’achat.</p><p>Un cours peut être reporté jusqu’à 24 heures avant le rendez-vous. À moins de 24 heures ou en cas d’absence, la séance est décomptée, sauf exception accordée par Animation Made. Si Animation Made doit annuler, un nouveau créneau est proposé sans frais ou la séance concernée est remboursée.</p></section>
    <section><h2>7. Droit de rétractation</h2><p>Le consommateur dispose en principe de 14 jours à compter de la conclusion du contrat pour se rétracter. Les modalités, le formulaire et les effets d’un commencement d’exécution anticipé sont détaillés sur la page <a href="/nouveau/remboursements">Rétractation et remboursements</a>.</p><p>Si le client demande expressément que la prestation commence avant la fin de ce délai, il reste redevable de la partie déjà exécutée s’il se rétracte avant l’exécution complète. Lorsque la prestation a été entièrement exécutée avant la fin des 14 jours, après demande expresse et reconnaissance de la perte du droit de rétractation, ce droit ne peut plus être exercé pour cette prestation.</p></section>
    <section><h2>8. Responsabilité du client et droits sur les contenus</h2><p>Le client garantit qu’il possède les droits nécessaires sur les travaux, images, vidéos, rigs, scènes, textes et références transmis. Il autorise Animation Made à les consulter, les annoter et les transformer uniquement pour réaliser la commande.</p><p>Le client reste responsable de ses choix artistiques, de ses sauvegardes, de ses candidatures, publications et usages ultérieurs. Animation Made répond de la bonne exécution de ses obligations dans les limites prévues par la loi.</p></section>
    <section><h2>9. Propriété intellectuelle et usage des livrables</h2><p>Les analyses, annotations, documents, méthodes et supports livrés sont destinés à l’usage personnel du client. Ils peuvent être utilisés pour retravailler et présenter son propre projet, mais ne peuvent pas être revendus, diffusés comme formation, reproduits publiquement ou mis à disposition de tiers sans accord écrit.</p></section>
    <section><h2>10. Réclamation et médiation</h2><p>En cas de difficulté, le client contacte d’abord <a href={`mailto:${businessIdentity.email}`}>{businessIdentity.email}</a> afin de rechercher une solution amiable. Les coordonnées du médiateur de la consommation choisi par Animation Made seront ajoutées avant l’ouverture des paiements au public.</p></section>
    <section><h2>11. Droit applicable</h2><p>Les présentes conditions sont soumises au droit français. Le consommateur conserve les protections impératives dont il bénéficie et peut saisir la juridiction compétente selon les règles applicables.</p></section>
  </LegalPage>;
}
