import LegalPage from "../_components/LegalPage";
import { businessIdentity } from "../_data/legal";

export const metadata = { title: "Confidentialité — Animation Made", description: "Politique de confidentialité et gestion des données personnelles sur Animation Made.", alternates: { canonical: "/nouveau/confidentialite" } };

export default function PrivacyPage() {
  return <LegalPage eyebrow="TES DONNÉES" title={<>Politique de <em>confidentialité.</em></>} intro="Cette page explique quelles données sont utilisées, pourquoi elles le sont et comment exercer tes droits.">
    <section><h2>Responsable du traitement</h2><p>{businessIdentity.owner}, entrepreneure individuelle exploitant Animation Made, est responsable des traitements décrits ici. Contact : <a href={`mailto:${businessIdentity.email}`}>{businessIdentity.email}</a>.</p></section>
    <section><h2>Données utilisées et finalités</h2><div className="am-legal-table" role="table" aria-label="Traitements de données"><div role="row"><strong role="columnheader">Données</strong><strong role="columnheader">Pourquoi</strong><strong role="columnheader">Base légale</strong></div><div role="row"><span>Identité, e-mail, compte et connexion</span><span>Créer et sécuriser ton espace, te reconnaître et t’assister</span><span>Exécution du contrat et intérêt légitime de sécurité</span></div><div role="row"><span>Commande, paiement et facturation</span><span>Encaisser, confirmer les droits d’accès et tenir la comptabilité</span><span>Contrat et obligations légales</span></div><div role="row"><span>Questionnaires, objectifs, liens, fichiers et travaux</span><span>Préparer et réaliser la prestation personnalisée</span><span>Exécution du contrat</span></div><div role="row"><span>Disponibilités et rendez-vous</span><span>Planifier les cours et transmettre les informations de visioconférence</span><span>Exécution du contrat</span></div><div role="row"><span>Messages adressés au support</span><span>Répondre aux demandes et gérer les litiges</span><span>Contrat et intérêt légitime</span></div><div role="row"><span>Préférences marketing, si proposées</span><span>Envoyer uniquement les communications acceptées</span><span>Consentement</span></div></div></section>
    <section><h2>Destinataires et prestataires</h2><p>Les données sont accessibles uniquement à Animation Made et, dans la limite nécessaire à leur mission, aux prestataires utilisés pour l’hébergement, l’authentification, la base de données et le stockage, le paiement, les e-mails, la visioconférence et la gestion éditoriale. La liste exacte est tenue à jour lors du branchement des services.</p><p>Certains prestataires peuvent traiter des données hors de l’Espace économique européen. Dans ce cas, Animation Made vérifie l’existence d’un mécanisme juridique approprié, notamment une décision d’adéquation ou des clauses contractuelles types.</p></section>
    <section><h2>Durées de conservation</h2><ul><li>Compte actif : pendant toute sa durée d’utilisation. Un compte resté inactif pendant 3 ans pourra être supprimé après avertissement.</li><li>Compte fermé : les données qui ne doivent pas être conservées pour une obligation légale sont supprimées ou anonymisées sous 30 jours.</li><li>Vidéos, pièces jointes et autres fichiers de travail : 6 mois après la dernière livraison liée à la commande.</li><li>PDF finaux, retours annotés et livrables : accessibles dans l’espace tant que le compte existe, puis supprimés sous 30 jours après sa fermeture. Le client est invité à en télécharger une copie.</li><li>Questionnaires et suivi de prestation : 3 ans après la fin de la commande.</li><li>Commandes, factures et pièces comptables : 10 ans.</li><li>Demandes adressées au support : le temps nécessaire à leur traitement, puis archivage en cas de litige pendant la durée de prescription applicable.</li><li>Données fondées sur ton consentement : jusqu’au retrait de celui-ci ou à la fin de la finalité concernée.</li></ul></section>
    <section><h2>Tes droits</h2><p>Tu peux demander l’accès à tes données, leur rectification, leur effacement, leur portabilité ou la limitation de leur traitement. Tu peux aussi t’opposer à certains traitements et retirer un consentement à tout moment, sans remettre en cause les opérations déjà réalisées.</p><p>Écris à <a href={`mailto:${businessIdentity.email}`}>{businessIdentity.email}</a>. Une preuve d’identité peut être demandée uniquement si cela est nécessaire pour éviter qu’un tiers accède à tes données. Tu peux également déposer une réclamation auprès de la <a href="https://www.cnil.fr/fr/plaintes" target="_blank" rel="noreferrer">CNIL</a>.</p></section>
    <section><h2>Cookies et stockage local</h2><p>Les éléments strictement nécessaires au fonctionnement, à la sécurité, à la sauvegarde temporaire des formulaires et au maintien de la session peuvent être utilisés sans finalité publicitaire. Tout outil de mesure d’audience ou de marketing non exempté sera soumis à ton choix avant son activation.</p></section>
  </LegalPage>;
}
