import LegalPage from "../_components/LegalPage";
import { businessIdentity } from "../_data/legal";

export const metadata = { title: "Rétractation et remboursements — Animation Made", description: "Droit de rétractation, reports, annulations et remboursements des offres Animation Made.", alternates: { canonical: "/nouveau/remboursements" } };

export default function RefundPage() {
  return <LegalPage eyebrow="APRÈS TA COMMANDE" title={<>Rétractation et <em>remboursements.</em></>} intro="Les règles diffèrent selon que la prestation a commencé, qu’un livrable a déjà été préparé ou qu’un cours doit être reporté.">
    <section><h2>Le délai légal de 14 jours</h2><p>Pour une commande conclue à distance, tu disposes en principe de 14 jours à compter de la commande pour te rétracter sans avoir à justifier ta décision.</p><p>Pour exercer ce droit, envoie une déclaration claire ou le formulaire ci-dessous à <a href={`mailto:${businessIdentity.email}`}>{businessIdentity.email}</a> avant la fin du délai.</p></section>
    <section><h2>Si tu demandes que la prestation commence immédiatement</h2><p>Pour recevoir une analyse, un document, un feedback ou un cours avant la fin des 14 jours, il pourra t’être demandé de confirmer expressément que tu souhaites commencer sans attendre.</p><ul><li>Si tu te rétractes alors que la prestation a commencé mais n’est pas terminée, le montant correspondant au travail déjà réalisé reste dû ; le solde est remboursé.</li><li>Si la prestation a été entièrement exécutée après ta demande expresse et ta reconnaissance de la perte du droit de rétractation, tu ne peux plus te rétracter pour cette prestation.</li><li>Si aucun travail n’a commencé et qu’aucun cours n’a eu lieu, le remboursement porte sur l’intégralité de la commande.</li></ul></section>
    <section><h2>Reports et annulations des cours</h2><p>Tu peux reporter un cours jusqu’à 24 heures avant l’horaire réservé. À moins de 24 heures ou en cas d’absence, la séance est décomptée, sauf exception accordée par Animation Made.</p><p>Si Animation Made annule une séance, tu choisis entre un nouveau créneau sans frais et le remboursement de la séance concernée. Pour un pack, le remboursement éventuel tient compte des séances déjà réalisées.</p></section>
    <section><h2>Retard ou impossibilité d’exécuter la prestation</h2><p>En cas de retard, contacte Animation Made par écrit. Lorsque les conditions légales sont réunies, tu peux demander l’exécution dans un délai supplémentaire raisonnable, puis résoudre le contrat si la prestation n’est toujours pas fournie. Les sommes dues sont alors remboursées dans le délai légal.</p></section>
    <section><h2>Formulaire type de rétractation</h2><div className="am-withdrawal-template"><p>À l’attention de : {businessIdentity.owner} — Animation Made<br/>{businessIdentity.address}<br/>{businessIdentity.email}</p><p>Je vous notifie par la présente ma rétractation du contrat portant sur la prestation suivante : […]</p><p>Commandée le : […]<br/>Nom du client : […]<br/>Adresse e-mail utilisée pour la commande : […]<br/>Numéro de commande : […]</p><p>Date : […]<br/>Signature, uniquement en cas d’envoi sur papier : […]</p></div></section>
    <section><h2>Délai de remboursement</h2><p>Lorsqu’un remboursement est dû, il est effectué au plus tard dans les 14 jours suivant la date à laquelle Animation Made est informée de la rétractation ou de la résolution applicable, avec le même moyen de paiement sauf accord contraire et sans frais supplémentaires.</p></section>
  </LegalPage>;
}
